### ISSUE TITLE
Turning Router on/off

### ISSUE THREAD

**Issue by ersdds** [WebControlCNC/WebControl#127]
I was wondering if any of the AUX outputs in Web Control Can Power the Router on/off

**Comment by Orob-Maslow** [comment]
Webcontrol is the software that communicates with the arduino controller.  The aux ports are on the arduino and can be activated by sending gcode such as M3 or M4 for different spin directions and M5 for off according to a github/grbl issue.  The M3 or M4 can be mapped to a macro button in webcontrol as can the M5.  Using the settings, you can change the button names so it will work from webcontrol, though since maslow is not totally grbl compliant, the commands may be slightly different.

**Comment by gb0101010101** [comment]
AUX1 on the Malsow controller board is mapped for router/spindle power. Use this to control an optional optically isolated relay.
Maslow firmware only supports router/spindle in one direction, so gcode M3 & M4 do the same thing, and will turn it on. Gcode M5 is off.
WebControl passes M3/4/5 commands to controller.

**Comment by ersdds** [comment]
Thanks for the clarification
