### ISSUE TITLE
Macro Buttons don't read Macro1_title or Macro2_title from groundcontrol.ini

### ISSUE THREAD

**Issue by wkellyoconnor** [WebControlCNC/WebControl#24]
I use Macro 1 and Macro 2 to start and stop the spindle. In groundcontrol.ini I have this: macro1_title = Router On
sledheight = 139
macro2 = M05
macro1 = M03
zaxis = 1
sledcg = 79
macro2_title = Router Off
But in WebControl both buttons still show: Macro 1 and Macro 2 but when pressed, they send the proper GCodes and the spindle turns on and off.

**Comment by madgrizzle** [comment]
Yeah, this is something from GC that I never really implemented.  I'll look into it, but relabeling buttons and reducing font size automatically to fit that text in I think is going to be a challenge (that's why I never got around to it).  I can implement a straight button text update, but the user may have to limit the number of characters themselves.

**Comment by BarbourSmith** [comment]
Yeah, resizing font to fit on a button is remarkably difficult. I really wish there was just an option for having the text fit

**Comment by wkellyoconnor** [comment]
Ok, I didn't know it was simply not implemented. If you ever do, I'd be happy to test fitting various size text.

**Comment by gb0101010101** [comment]
Created [pull request](https://github.com/madgrizzle/WebControl/pull/97) with quick fix to display custom macro title truncated to 6 characters.

**Comment by madgrizzle** [comment]
Merged into master.  Closing.
